Cr dev
js-data/js-data-mongodb pull request #29
Opened 2016-09-23 05:24 UTC by crobinson42

Fixes #21 

> Note: This project uses `semantic-release` to auto publish npm packages on successful builds.
The commit messages must follow AngularJS Commit Msg Conventions: https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.uyo6cb12dt6w

- [x] - My commit messages follow AngularJS Commit Msg Conventions
- [] - If applicable, appropriate JSDoc comments were updated in source code
- [ ] - If applicable, appropriate changes to js-data.io docs have been suggested ("Suggest Edits" button)
- [x] - Unit test coverage did not decrease & appropriate tests changes made

2016-09-27 04:07 UTC, jmdobry commented
Why does it say merging will decrease coverage by 15%?

2016-09-27 04:14 UTC, crobinson42 commented
I'm unsure about codecov reports. When I started on the branch coverage was
in the 70% range. Is it reporting coverage diff from a release?

On Sep 26, 2016 9:07 PM, "Jason Dobry" <notifications@github.com> wrote:

> Why does it say merging will decrease coverage by 15%?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/js-data/js-data-mongodb/pull/29#issuecomment-249761416>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AFsmS5DTA0ZDeGcHmLn5P6CCLKaEtK2Uks5quJZ4gaJpZM4KEnvW>
> .
>

2016-09-30 17:32 UTC, crobinson42 commented
@jmdobry Any thoughts, ideas, or recommendations on this PR?

Also, any idea on the hanging codecov status? I'm sure the code coverage isn't decreasing.. am I missing something here?

2016-10-02 17:17 UTC, jmdobry requested changes

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +  convertMongo_id: false,
Can we change this option to be fully camelCase?

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +   * @type {Boolean}
`{Boolean}` => `{boolean}`

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +  /* istanbul ignore if */
Why are we ignoring this?

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +    if (!r) return r
`if (!r) return r`

=>

```js
if (!r) {
  return r
}
```

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +      if (typeof r !== 'object') return
`if (typeof r !== 'object') return`

=>

```js
if (!utils.isObject(r)) {
  return
}
```

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +  _convertMongo_id (d, opts) {
Can we make this method name fully camelCase?

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +    if (!d) return
`if (!d) return` =>

```js
if (!d) {
  return
}
```

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +  _convertMongo_id (d, opts) {
Can we use a more descriptive variable name than `d`?

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
>    _translateFieldObjectIDs (r) {
Can we use a more descriptive variable name than `r`?

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +  _translateId (r, opts) {
Can we use a more descriptive variable name than `r`?

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
>    _translateObjectIDs (r, opts) {
Can we use a more descriptive variable name than `r`?

2016-10-02 17:17 UTC, jmdobry commented on src/index.js
> +    const convert = (x) => {
Can we pull this out into a top-level standalone function? It doesn't look like it needs to create a closure over anything.

2016-10-05 17:27 UTC, closed without merging